### ISSUE TITLE
会有版权纠纷吗

### ISSUE THREAD

**Issue by mysmlz** [zhuifengshen/xmind#20]
毕竟人家是商业软件,虽然.xmind文件相当于是开放给大家看了

**Comment by MasterYip** [comment]
其实在xmind公司github仓库中有[xmindltd / xmind-sdk-python](https://github.com/xmindltd/xmind-sdk-python)的MIT开源项目，这个项目是基于此项目二次开发的，完善了更多功能。版权问题可以参考MIT协议~
