### ISSUE TITLE
生成的文件xmind打不开，是不是版本问题

### ISSUE THREAD

**Issue by SeekPoint** [zhuifengshen/xmind#3]
XMind-ZEN-Update-2019-for-Windows-64bit-9.1.3.201812101752.exe

我用的win10, python3

**Comment by DawnGnius** [comment]
Same problem meet with Xmind-Zen, but doesn't occur when using Xmind-8.
For detail:
1. Linux-x64-4.15.0-42-generic-201807162014-vana_linux_64
Using python3, Xmind-Zen
Cannot open the file generated.
2. Xmind-8 on Linux
It works normally.

**Comment by AustEcon** [comment]
Same problem for me too. I used the trial version of xmind ZEN on windows 10.
Does this library only work with xmind 8 ?

**Comment by jingle1267** [comment]
Same problem for me too. I used the trial version of xmind ZEN on MBP10.14.4.

**Comment by arthur657834** [comment]
@zhuifengshen  大佬这个问题修不修的？

**Comment by jingle1267** [comment]
用最新版的xmind软件无法打开生成的xmind格式的文档，老版本的可以。不知道是xmind格式升级了，还是新版软件的bug。

**Comment by hao44le** [comment]
xmind8 works. Xmind Zen doesn't work

**Comment by zhuifengshen** [comment]
> @zhuifengshen 大佬这个问题修不修的？

暂时只支持XMind8，不支持XMind Zen
