### ISSUE TITLE
二维码失效了

### ISSUE THREAD

**Issue by zhouweisong** [zhuifengshen/xmind#4]
微信号 17610086125 希望能拉我进群 谢谢~~

**Comment by cdmalcl** [comment]
![python](https://user-images.githubusercontent.com/8749073/59035070-0a918f80-889f-11e9-85aa-e1d928eeeff1.jpg)
直接弄个这个吧

**Comment by zhuifengshen** [comment]
好，后续我重新组织一下

**Comment by wanghuohuo0716** [comment]
有新的二维码么，求拉入群！
